<a href="https://colab.research.google.com/github/essymizo/GIS_MachineLearning/blob/main/Python_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
for i in [0,1,2]:
  print(i)
  print('Done')
print('Stop')

0
Done
1
Done
2
Done
Stop


In [ ]:
a=1
b=3
c=1
print('is a greater than b OR not equal to c:', (a>b)|(a!=c))
print('is a greater than b AND not equal to c:', (a>b)&(a!=c))

is a greater than b OR not equal to c: False
is a greater than b AND not equal to c: False


In [ ]:
def test_func(a,b):
  if a>b:
    print("a is bigger")
  elif a<b:
    print("a is lesser")
  else:
    print("ola")

In [ ]:
test_func(3,8)

a is lesser


In [ ]:
import numpy as np


In [ ]:
a=[1,2,'hi']
print(a[-1])
print(type(a))
b=np.array(a)
print(type(b))

hi
<class 'list'>
<class 'numpy.ndarray'>


In [ ]:
a=np.ones((3,4,2))
print(a)
a.shape

[[[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]]


(3, 4, 2)

In [ ]:
a=np.arange(0,31,2,int)
#print(a)
a.shape
b=a.reshape(4,-1)
print(b,'\n',b.shape)


[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]
 [24 26 28 30]] 
 (4, 4)


In [ ]:
print(b[2:])

[[16 18 20 22]
 [24 26 28 30]]


In [ ]:
print(b[:2,2:])

[[ 4  6]
 [12 14]]
